export default interface Annotation {
    /**
    * UUID to identify the object
    */
    id: string
    /**
    * Start time to show on the player
    */
    startTime: number
    /**
    * End time to show on the player
    */
    endTime: number
    /**
    * Player height when the annotation was created
    */
    playerHeight: number
    /**
    * Player width when the annotation was created
    */
    playerWidth: number
    /**
    * Color of the annotation
    */
    color: string
    /**
    * Json generated by fabricjs
    */
    fabricJson: string
    /**
    * Not used by the player, just for convenience
    */
    data?: any
}